[bastion_hosts]
ops-server-01 ansible_host=47.129.231.63

[bastion_hosts:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/ops-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
zabbix_server_ip=10.97.10.100