apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-frontend
  labels:
    app: cms-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-frontend
  template:
    metadata:
      labels:
        app: cms-frontend
    spec:
      containers:
      - name: frontend
        #image: cms-97-frontend:latest 
        image: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/frontend:latest
        ports:
        - containerPort: 80 
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "http://backend-service:8000"
        - name: API_URL
          value: "http://backend-service:8000"